name: jetleaf_core
description: The core runtime that powers JetLeafâ€™s pod, context, and app lifecycle.
version: 1.1.3

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_core
issue_tracker: https://github.com/jetleaf/jetleaf_core/issues
documentation: https://jetleaf.hapnium.com/docs/core

topics:
  - ioc
  - jetleaf
  - context
  - lifecycle
  - application-core

keywords:
  - ioc
  - jetleaf
  - service-locator
  - context
  - pod

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.2
  jetleaf_logging: ^1.1.2
  jetleaf_convert: ^1.1.2
  jetleaf_utils: ^1.1.2
  jetleaf_env: ^1.1.3
  jetleaf_pod: ^1.1.2

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0